Vagrant.configure("2") do |config|
  # Configuración para el primer nodo
  config.vm.define "manager" do |manager|
	manager.vm.box = "bento/ubuntu-22.04"
	manager.vm.hostname = "manager"
    manager.vm.network "private_network", ip: "192.168.33.10"
    manager.vm.network "forwarded_port", guest: 80, host: 8000
    manager.vm.provision "shell", inline: <<-SHELL
      # Instalar Docker según procedimientos oficiales
      curl -fsSL https://get.docker.com -o get-docker.sh
      sudo sh get-docker.sh
      sudo usermod -aG docker vagrant
    SHELL
    manager.vm.synced_folder ".", "/vagrant"
  end

  # Configuración para el segundo nodo
  config.vm.define "nodo1" do |nodo1|
    nodo1.vm.box = "bento/ubuntu-22.04"
	nodo1.vm.hostname = "nodo1"
    nodo1.vm.network "private_network", ip: "192.168.33.11"
    nodo1.vm.network "forwarded_port", guest: 80, host: 8001
    nodo1.vm.provision "shell", inline: <<-SHELL
      # Instalar Docker según procedimientos oficiales
      curl -fsSL https://get.docker.com -o get-docker.sh
      sudo sh get-docker.sh
      sudo usermod -aG docker vagrant
    SHELL
    nodo1.vm.synced_folder ".", "/vagrant"
  end
end
